import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import PageTransition from "./components/PageTransition";
//import StairTransition from "./components/StairTransition";
import ParabolaTransition from "./components/ParabolaTransition";


const montserratAlternates = Montserrat_Alternates({
  subsets: ['latin'], // Specify subsets
  weight: ['400', '700'], // Specify font weights
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlternates.className} antialiased`}
      >
        <ParabolaTransition>
            <Header />
            {children}
        </ParabolaTransition>
      </body>
    </html>
  );
}
